github.com:
    users:
        D-Zoro:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: D-Zoro
